global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # ServiceDesk Application
  - job_name: 'servicedesk'
    static_configs:
      - targets: ['app:3000']
        labels:
          service: 'servicedesk-app'

  # PostgreSQL Exporter (optional)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
        labels:
          service: 'postgres'

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

